### ISSUE TITLE
no module error

### ISSUE THREAD

**Issue by ShaoManli** [dagghe/PyOMA#1]
If I use the example with Python 3.8.8, there comes: ModuleNotFoundError: No module named 'pyOMA'

**Comment by dagghe** [comment]
Hi,
try: "import PyOMA" (with capital P)

**Comment by ShaoManli** [comment]
Hi, thank you, it worked out with Capital P.

_# to retrieve the example data -> there I get this error:_
_module 'PyOMA' has no attribute 'Exdata'_

**Comment by braidoj** [comment]
Hi, 

Using the "Example.py" file on Spyder (Python 3.9) gives the message: 

"AttributeError: module 'PyOMA' has no attribute 'FDDsvp'"

**Comment by marco-rosso-m** [comment]
Hi, 

I solved the issues of importing after pip install by adding this [file](https://github.com/dagghe/PyOMA/blob/master/PyOMA/__init__.py).

So, after pip install the PyOMA module, in order to make it work when imported e.g. in Anaconda Spyder IDE, it is necessary look for the installed packages folder (C:\ProgramData\Anaconda3\Lib\site-packages\PyOMA) and paste here the file __init__.py . Now, when import PyOMA as oma in Spyder IDE it will work and load all the functions inside the PyOMA module.

**Comment by trantrieuvy** [comment]
Hi,
Can you please upload the init.py file again? the link doesn't work anymore

**Comment by Kdemirlioglu** [comment]
Hi! The error ("AttributeError: module 'PyOMA' has no attribute 'FDDsvp'") is still available. Could you please upload the init.py file again or tell us the solution?

**Comment by marco-rosso-m** [comment]
Hello @Kdemirlioglu and @trantrieuvy , 

I have fixed the problem through the pip install command. Now it will directly install also the __init__.py file which is necessary to import the functions inside the PyOMA.py module.

Please refer to the command pip install Py-OMA published [here](https://pypi.org/project/Py-OMA/)

**Comment by marco-rosso-m** [comment]
Hello,

I have fixed the problem through the pip install command. Now it will directly install also the __init__.py file which is necessary to import the functions inside the PyOMA.py module.

Please refer to the command pip install Py-OMA published [here](https://pypi.org/project/Py-OMA/)

Hopefully this was helpful

Best regards


Marco Martino Rosso



ArtIStE - Artificial Intelligence in Structural Engineering<http://www.civilml.polito.it/>

e-mail: ***@***.******@***.***>

Personal Website<http://rossomarcomartino.flazio.com/>

PhD Student in Structural Civil Engineering at Politecnico di Torino

________________________________
Da: Kultigin Demirlioglu ***@***.***>
Inviato: venerdì 16 settembre 2022 17:54
A: dagghe/PyOMA ***@***.***>
Cc: Rosso Marco Martino ***@***.***>; State change ***@***.***>
Oggetto: Re: [dagghe/PyOMA] no module error (#1)


Hi! The error ("AttributeError: module 'PyOMA' has no attribute 'FDDsvp'") is still available. Could you please upload the init.py file again or tell us the solution?
