### ISSUE TITLE
mode shapes acquired through cov-SSI

### ISSUE THREAD

**Issue by Ayubirad** [dagghe/PyOMA#17]
Hi there,
First of all thanks for this great package. I've been having trouble acquiring the correct mode shapes using cov-SSI. I received the correct results when I substituted the lines 550-557 with these:

```
    class auxclass(np.ndarray):
        """
        Create a simple class to improve code readability
        """
       
        def __new__(cls, np_array):

            return np.asarray(np_array).view(cls)
        
    N = ndat-2*br+1
    r = l = nch
    i = br

    Ypref = np.zeros((r*i,N))
    Yf    = np.zeros((l*i,N))
        
    for k in range(i):
        Ypref[k*r:k*r+r,:] = Yy[:r,k:k+N]
        Yf   [k*l:k*l+l,:] = Yy[: ,k+i:k+i+N]
        
    Ypref = Ypref/N**0.5
    Yf    = Yf   /N**0.5
    
    # Assembling the Toepliz matrix    
    Tb   = auxclass(Yf @ Ypref.T)
```

Could you please look into this?

Best regards,

**Comment by dagghe** [comment]
Dear Ayubirad,
Thank you for your feedback.
If i understand correctly you have problems with the code lines concerning the construction of the block Toeplitz matrix of correlations, is it correct? However, I will look into the code you've posted and come back to you, but it would help if you could clarify what you mean with "I've been having trouble acquiring the correct mode shapes using cov-SSI". Do you mean that you get "wrong" mode shapes or that the code fail to execute?

Best regards,

Dag

**Comment by Ayubirad** [comment]
Exactly, and yes I got the wrong modeshapes!
However, the issue was fixed using the lines I sent you.
I really appreciate your help.

Best regards,
Ayubirad

**Comment by dagghe** [comment]
Dear Ayubirad,
could you please provide the dataset that gives you the wrong shapes with SSI-cov? I've tested the function with several dataset (real and simulated) and never encountered such problem, so it would really help if you could provide the "incriminated" dataset.

Best regards

Dag

**Comment by Ayubirad** [comment]
Sure, here's the link to the data with Fs=50 Hz (impact load). I've also added the mode shapes matrices corresponding to SSI-cov acquired through pyoma and the code I'd sent you. As you can see, aside from the wrong mode shapes, the pyoma SSI-cov could not find some of the modes whereas the other script could.

[https://easyupload.io/2kx8tn](url)

All the best,
Ayubirad

**Comment by Ayubirad** [comment]
Dear Dag,

Another thing I forgot to mention is the difference between damping ratio estimated by EFDD and SSI. I'd compared the results for the dataset. Is this behavior expected?

[https://easyupload.io/2xgysc](url)

All the best,
Ayubirad
