### ISSUE TITLE
Exdata() func

### ISSUE THREAD

**Issue by pbtank** [dagghe/PyOMA#3]
I am interested in the exdata() func of your code. Can you please give me some references (any kind of book or paper you followed) for how the state space representation can be solved for structural responses?

**Comment by dagghe** [comment]
Hi,
sorry for the late reply!
The example itself (geometry, mass matrix, stiffness matrix) comes from Chopras's Dynamic of Structures. When it comes to state space modelling here comes the literature i found most useful to study the topic.
R. Brincker and C. Ventura, Introduction to operational modal analysis. John Wiley &Sons, 2015.
C. Rainieri and G. Fabbrocino, “Operational modal analysis of civil engineering structures, Springer, New York, 2014
B. Peeters, System identification and damage detection in civil engeneering. Katholieke Universiteit te Leuven, 2000
P. Van Overschee and B. De Moor,Subspace identification for linear systems:  Theory Implementation Applications. Springer Science & Business Media, 2012.

**Comment by pbtank** [comment]
Okay got it. Thanks.
