### ISSUE TITLE
Error in EFDDmodEX

### ISSUE THREAD

**Issue by Ayubirad** [dagghe/PyOMA#7]
Hi there, I want to thank you for this great contribution. I've sent the problem I encountered using EFDD. As you can see I've used the provided example file. It seems the problem lies in the calculation of the Singular Vectors:
```
  File "c:\...\pyoma-master\example\example.py", line 57, in <module>
    Res_EFDD = oma.EFDDmodEX(FreQ, FDD[1], method='EFDD')

  File "C:\...\PyOMA-master\Example\pyOMA.py", line 1149, in EFDDmodEX
    meanFi = meanFi/meanFi[_idx6]

IndexError: invalid index to scalar variable.
```

**Comment by dagghe** [comment]
Hi, sorry for the delay.
Could you provide more details to reproduce the error?
Have you tried to change the arguments you are passing to the function?  What I mean is: double check that the frequencies you are searching for (the FreQ argument) are actually peaks in the PSD plot, then try to increase the ndf parameter (number of spectral lines in the proximity of FreQ[i] where the peak is searched and/or lower the MaClim argument... let me know how it goes...

**Comment by Ayubirad** [comment]
Thanks for the reply,
I just ran the `Example.py` file provided in the Example folder. Data are generated as described in the script using:

 `data, (fex, FI_ex, xi_ex) = oma.Exdata()`

and then as written in the Example.py:

```
# Sampling frequency
fs = 100 # [Hz] Sampling Frequency

# Using SciPy's signal module we can pre-process our data e.g. performing
# decimation, trend removal and filtering. 
# Detrend and decimate
data = signal.detrend(data, axis=0) # Trend rmoval
q = 5 # Decimation factor
data = signal.decimate(data,  q, ftype='fir', axis=0) # Decimation
fs = fs/q # [Hz] Decimated sampling frequency

# Filter
_b, _a = signal.butter(12, (0.3,6.5), fs=fs, btype='bandpass')
filtdata = signal.filtfilt(_b, _a, data,axis=0) # filtered data


# ======== ANALYSIS ===========================================================
# Run FDD
FDD = oma.FDDsvp(data,  fs)
# FDD = FDDsvp(filtdata,  fs)

# Define list/array with the peaks identified from the plot
FreQ = [0.89, 2.6, 4.1, 5.27, 6] # identified peaks

# Extract the modal properties 
Res_FDD = oma.FDDmodEX(FreQ, FDD[1])
Res_EFDD = oma.EFDDmodEX(FreQ, FDD[1], method='EFDD')
```

and the aforementioned error pops up!

**Comment by dagghe** [comment]
Yeah there is definitely something wrong/strange with the behaviour of "FDDmodEX" and "EFDDmodEX" functions... I will do some testing and try to fix the issue as soon as possible... Thank you for the feedback!

**Comment by Ayubirad** [comment]
Thank you!
